name       : python-backports.functools_lru_cache
version    : '1.5'
release    : 5
source     :
    - https://files.pythonhosted.org/packages/source/b/backports.functools_lru_cache/backports.functools_lru_cache-1.5.tar.gz : 9d98697f088eb1b0fa451391f91afb5e3ebde16bbdb272819fd091151fda4f1a
homepage   : https://github.com/jaraco/backports.functools_lru_cache
license    : MIT
component  : programming.python
summary    : Backport of functools.lru_cache from Python 3.3
description: |
    Backport of functools.lru_cache from Python 3.3
builddeps  :
    - python-setuptools
    - python2-setuptools-scm
    - python2-pytest
rundeps    :
    - python-backports
build      : |
    %python_setup
install    : |
    %python_install
    rm $installdir/usr/lib/python2.7/site-packages/backports/__init__.py*
check      : |
    %python_test pytest -v
